title: Screenshots
tagline: Open Source Design Inspiration
description: A GitHub Pages screenshot gallery.
project_url: https://github.com/joesteinkamp/screenshots-design-inspiration

permalink: pretty


google_analytics: UA-8657893-8
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag



tag_page: '/tags/'

exclude:
  - "*/tags.json"
  - scripts/
  - node_modules/